### ISSUE TITLE
RemoteNetwork gives an error when explicit provider host is not set

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-scm#35]
### Describe what happened

upstream https://github.com/PaloAltoNetworks/terraform-provider-scm/issues/20

### Sample program

n/a

### Log output

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by zbuchheit** [comment]
According to the PaloAlto team this is working as intended just wasn't documented correctly.
